version: "3.3"
services:
  worker:
    container_name: worker
    restart: on-failure
    network_mode: bridge
    build:
      context: ./worker
      dockerfile: worker.Dockerfile
    volumes: 
    - "./data:/app/data"
  api:
    container_name: api
    restart: on-failure
    network_mode: bridge
    build:
      context: ./api
      dockerfile: api.Dockerfile
    volumes: 
    - "./data:/app/data"
    ports:
    - "4000:3000"
  redis:
    container_name: redis
    restart: on-failure
    network_mode: bridge
    image: redis
